apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ollama.yaml
  - ollama-models-configmap.yaml
  - ollama-model-pull-job.yaml
  - openwebui-pvc.yaml
  - openwebui-deploy.yaml
  - openwebui-svc.yaml
  - openwebui-ing.yaml
