apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ollama.yaml
  - ollama-model-pull-job.yaml
  - openwebui-pvc.yaml
  - openwebui-deploy.yaml
  - openwebui-svc.yaml
  - openwebui-ing.yaml

configMapGenerator:
  - name: ollama-models
    namespace: chatbot
    files:
      - models.txt=models.txt

generatorOptions:
  disableNameSuffixHash: true
